spring.jpa.hibernate.ddl-auto=validate

# Dev DB
spring.datasource.url=jdbc:postgresql://localhost:5440/readflow
spring.datasource.username=postgres
spring.datasource.password=postgres

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:4173

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
